### ISSUE TITLE
Override flag not working as intended

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/plugin-rtc#14]
Carter (@crtr0) found a bug in the way the `--override` flag works. I had a look at the source code and I think I found the issue. 

## Current behavior
When you pass `--override` it will actually delete the existing service and generate a new one. The problem with this is that it will create a new URL because the number in the URL pattern: `<name>-<number>-<environment>.twil.io` is being changed. 

https://github.com/twilio-labs/plugin-rtc/blob/9544d2b9ddf3fcce4a1b727b843c81bd49d07555/src/commands/rtc/apps/video/deploy.js#L21-L23

## Expected behavior
The URL stays the same and only the code is being updated.

## The fix
I checked and you are using `@twilio-labs/serverless-api` to perform the deployment. 

https://github.com/twilio-labs/plugin-rtc/blob/9544d2b9ddf3fcce4a1b727b843c81bd49d07555/src/helpers.js#L125-L148

Instead of passing in the `serviceName` for the redeployment you should pass in `serviceSid` as shown here:
https://github.com/twilio-labs/serverless-api/blob/ee1c171113f9bd3368cbdd82b0f2cf4fee5c8f1c/src/client.ts#L382-L392

This will cause a redeployment to the same service and remove the need for deleting the service. It will also keep the same URL.

**Comment by aaalaniz** [comment]
Hey @dkundel 

I took a look at this issue, and the request makes sense. I made some progress on [this branch](https://github.com/twilio-labs/plugin-rtc/tree/task/improve-override-flag). I have the override working fine with only the token server, but ran into an issue with overriding assets.

I'll let you know when this has been completed!

**Comment by aaalaniz** [comment]
Fixed in #19
