### ISSUE TITLE
Unnecessary to set account sid / secret in function environment?

### ISSUE THREAD

**Issue by jesperfj** [twilio-labs/plugin-rtc#18]
https://github.com/twilio-labs/plugin-rtc/blob/e4e4f930da74a6f76369d98a18b8f953184577bf/src/helpers.js#L127-L129

I believe it is unnecessary to copy account sid and secret to the function. Functions already have the account sid and secret of the account that owns them. They are available as `context.ACCOUNT_SID` and `context.AUTH_TOKEN`

**Comment by timmydoza** [comment]
Thanks for the tip @jesperfj!

It's true that `ACCOUNT_SID` is already available on the `context` object, so there's no need to pass that in.  However, `AUTH_TOKEN` cannot be used to mint video tokens. We will still need to pass in `TWILIO_API_KEY_SID` and `TWILIO_API_KEY_SECRET`.

I've created a PR to address your feedback: https://github.com/twilio-labs/plugin-rtc/pull/20

**Comment by aaalaniz** [comment]
Fixed in #20 

Thanks!

**Comment by jesperfj** [comment]
Why can it be used to mint twilio client tokens but not video tokens?
