### ISSUE TITLE
Is there a way to deploy twilio-video using my own custom domain? 

### ISSUE THREAD

**Issue by RusseII** [twilio-labs/plugin-rtc#26]
When I deploy, the domain name is set to `video-app-XXXX-dev.twil.io`

Is there a way to still deploy to twilio serverless, and use my own domain? 

For example, host the app with `live.deephire.com`? 

I saw [this](https://www.twilio.com/docs/runtime/functions-assets-api#understanding-domains) in the twilio docs, but it didn't seem relevant to what I am looking for.

**Comment by aaalaniz** [comment]
Hey everyone,

This issue is not currently on our roadmap and we have decided to pursue other priorities. I will reopen if anything changes.
