### ISSUE TITLE
Unmet Dependency when running as Twilio-cli plugin

### ISSUE THREAD

**Issue by tobyallen** [twilio-labs/plugin-rtc#30]
XXXXX % twilio plugins:update
warning "@twilio-labs/plugin-rtc > @oclif/command@1.5.19" has unmet peer dependency "@oclif/plugin-help@^2".

Node Version 14.2

**Comment by kolbeypruitt** [comment]
Try this:
`upgrade the Twilio CLI plugin: twilio plugins:update`
then
`twilio rtc:apps:video:delete`
then
`npm run deploy:twilio-cli`

**Comment by valaykothari** [comment]
thank you it's working now.
